import = ["/home/abid/.config/alacritty/themes/themes/tokyo-night-storm.toml"]

[env]
TERM = "xterm-256color"

[colors.cursor]
cursor = "#FF4057"
text = "#000000"

[font]
size = 15
# offset.x = 0
offset.y = 6
glyph_offset.y = 3

[font.normal]
family = "monospace"
style = "normal"

[[keyboard.bindings]]
action = "ToggleFullScreen"
key = "F11"

[window]
blur = true
decorations = "none"
opacity = 0.95
