vim.o.cursorline = true
vim.o.number = true
vim.o.relativenumber = true
vim.o.scrolloff = 8
vim.o.updatetime = 100
vim.o.tabstop = 2
vim.o.shiftwidth = 2
vim.o.signcolumn = 'yes'
vim.o.mouse = ''
-- vim.o.foldmethod = 'expr'
-- vim.o.foldexpr = 'nvim_treesitter#foldexpr()'
vim.o.foldenable = false
vim.o.signcolumn = 'yes:1'
vim.o.fixeol = false
vim.o.fixendofline = false
vim.o.guifont = "Google Sans Mono:h19"
vim.g.neovide_opacity = 0.95
-- vim.g.neovide_floating_blur_amount_x = 0.9
-- vim.g.neovide_floating_blur_amount_y = 0.9
-- vim.g.neovide_window_blurred = true
vim.o.linespace = 6
vim.o.termguicolors = true
vim.g.neovide_cursor_smooth_blink = true
vim.g.neovide_input_use_logo = 1
